# Generated by Django 6.0.7 on 2026-07-28 20:50

import django.db.models.deletion
import main.content_utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company_content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HonorCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='分类名称')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='固定 slug')),
                ('description', models.CharField(blank=True, max_length=300, verbose_name='分类说明')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
            ],
            options={
                'verbose_name': '荣誉分类',
                'verbose_name_plural': '荣誉分类',
                'ordering': ('sort_order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='Honor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=120, unique=True, verbose_name='固定 slug')),
                ('title', models.CharField(max_length=200, verbose_name='荣誉名称')),
                ('summary', models.TextField(blank=True, verbose_name='公开摘要')),
                ('reference_number', models.CharField(blank=True, max_length=100, verbose_name='证书/公告编号')),
                ('issuer', models.CharField(blank=True, max_length=200, verbose_name='颁发/认定机构')),
                ('awarded_on', models.DateField(blank=True, null=True, verbose_name='获得日期')),
                ('display_image', models.ImageField(blank=True, upload_to='honors/images/', validators=[main.content_utils.validate_image_upload], verbose_name='展示图片')),
                ('document', models.FileField(blank=True, upload_to='honors/documents/', validators=[main.content_utils.validate_pdf_upload], verbose_name='公开 PDF')),
                ('use_watermark', models.BooleanField(default=False, verbose_name='展示图使用水印')),
                ('allow_document_download', models.BooleanField(default=False, verbose_name='允许下载 PDF')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('published', '已发布'), ('archived', '归档')], default='draft', max_length=20, verbose_name='状态')),
                ('verification_status', models.CharField(choices=[('pending', '待核验'), ('verified', '已核验'), ('rejected', '已拒绝')], db_index=True, default='pending', max_length=20, verbose_name='核验状态')),
                ('is_demo', models.BooleanField(db_index=True, default=False, verbose_name='演示内容')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='company_content.contentsource', verbose_name='内容来源')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='honors', to='honors.honorcategory', verbose_name='分类')),
            ],
            options={
                'verbose_name': '荣誉资质',
                'verbose_name_plural': '荣誉资质',
                'ordering': ('sort_order', '-awarded_on', 'id'),
            },
        ),
    ]
