# Generated by Django 6.0.7 on 2026-07-29 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('honors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='honor',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='内容核验时间'),
        ),
    ]
