# Generated by Django 6.0.7 on 2026-07-25 09:39

import django.db.models.deletion
import main.content_utils
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='分类名称')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='固定 slug')),
                ('description', models.CharField(blank=True, max_length=300, verbose_name='分类说明')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '新闻分类',
                'verbose_name_plural': '新闻分类',
                'ordering': ('sort_order', 'id'),
                'indexes': [models.Index(fields=['is_active', 'sort_order'], name='news_newsca_is_acti_1f1057_idx')],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='新闻标题')),
                ('slug', models.SlugField(max_length=180, unique=True, verbose_name='固定 slug')),
                ('summary', models.CharField(blank=True, max_length=300, verbose_name='摘要')),
                ('body', models.TextField(verbose_name='新闻正文')),
                ('body_text', models.TextField(blank=True, editable=False, verbose_name='正文纯文本')),
                ('cover', models.ImageField(blank=True, upload_to='news/original/', validators=[main.content_utils.validate_image_upload], verbose_name='新闻封面')),
                ('cover_web', models.ImageField(blank=True, editable=False, upload_to='news/web/', verbose_name='网页封面')),
                ('cover_thumb', models.ImageField(blank=True, editable=False, upload_to='news/thumbs/', verbose_name='封面缩略图')),
                ('cover_alt', models.CharField(blank=True, max_length=200, verbose_name='封面 Alt')),
                ('focal_x', models.FloatField(default=0.5, verbose_name='焦点 X')),
                ('focal_y', models.FloatField(default=0.5, verbose_name='焦点 Y')),
                ('source', models.CharField(default='华丽电器', max_length=100, verbose_name='公开来源')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='发布时间')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('published', '已发布'), ('archived', '归档')], default='draft', max_length=20, verbose_name='状态')),
                ('is_featured', models.BooleanField(default=False, verbose_name='首页推荐')),
                ('featured_order', models.PositiveIntegerField(default=0, verbose_name='推荐排序')),
                ('seo_title', models.CharField(blank=True, max_length=160, verbose_name='SEO 标题')),
                ('seo_description', models.CharField(blank=True, max_length=300, verbose_name='SEO 描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_articles', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_articles', to=settings.AUTH_USER_MODEL, verbose_name='最后修改人')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='articles', to='news.newscategory', verbose_name='新闻分类')),
            ],
            options={
                'verbose_name': '新闻',
                'verbose_name_plural': '新闻',
                'ordering': ('-published_at', '-id'),
                'indexes': [models.Index(fields=['status', 'published_at'], name='news_articl_status_f1b279_idx'), models.Index(fields=['category', 'status', 'published_at'], name='news_articl_categor_365f13_idx'), models.Index(fields=['is_featured', 'featured_order'], name='news_articl_is_feat_9a736b_idx')],
            },
        ),
    ]
