# Generated by Django 6.0.7 on 2026-07-25 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='first_published_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='首次发布时间'),
        ),
    ]
