# Generated by Django 6.0.7 on 2026-07-28 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_article_first_published_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_demo',
            field=models.BooleanField(db_index=True, default=False, verbose_name='演示新闻'),
        ),
        migrations.AddField(
            model_name='article',
            name='source_url',
            field=models.URLField(blank=True, verbose_name='来源网址'),
        ),
        migrations.AddField(
            model_name='article',
            name='verification_status',
            field=models.CharField(choices=[('pending', '待核验'), ('verified', '已核验'), ('rejected', '已拒绝')], db_index=True, default='pending', max_length=20, verbose_name='核验状态'),
        ),
        migrations.AddField(
            model_name='article',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='核验时间'),
        ),
    ]
