"""
Django settings for huali_website project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY", "local-development-key-not-valid-for-production-2026")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DJANGO_DEBUG", "true").lower() == "true"

ALLOWED_HOSTS = [item.strip() for item in os.getenv("ALLOWED_HOSTS", "localhost,127.0.0.1").split(",") if item.strip()]
SITE_URL = os.getenv("SITE_URL", "http://localhost:5173").rstrip("/")
SITE_DOMAIN = os.getenv("SITE_DOMAIN", "localhost")
SITE_CONTENT_MODE = os.getenv("SITE_CONTENT_MODE", "test").strip().lower()
if SITE_CONTENT_MODE not in {"test", "production"}:
    raise ValueError("SITE_CONTENT_MODE 只能是 test 或 production。")
SQLITE_BUSY_TIMEOUT_MS = int(os.getenv("SQLITE_BUSY_TIMEOUT_MS", "5000"))


# Application definition

INSTALLED_APPS = [
    'simpleui',
    'rest_framework',
    'drf_spectacular',
    'django_otp',
    'operations.third_party_apps.ChineseTotpConfig',
    'operations.third_party_apps.ChineseAxesConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'products.apps.ProductsConfig',
    'news.apps.NewsConfig',
    'company_content.apps.CompanyContentConfig',
    'honors.apps.HonorsConfig',
    'page_builder.apps.PageBuilderConfig',
    'main.apps.MainConfig',
    'operations.apps.OperationsConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django_otp.middleware.OTPMiddleware',
    'axes.middleware.AxesMiddleware',
    'operations.middleware.SuperuserTwoFactorMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'operations.middleware.SameOriginFrameMiddleware',
]

ROOT_URLCONF = 'huali_website.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'huali_website.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': Path(os.getenv("DATABASE_PATH", BASE_DIR / "db.sqlite3")),
        'OPTIONS': {'timeout': SQLITE_BUSY_TIMEOUT_MS / 1000},
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'frontend' / 'public']
STATIC_ROOT = Path(os.getenv("STATIC_ROOT", BASE_DIR / "staticfiles"))

MEDIA_URL = '/media/'
MEDIA_ROOT = Path(os.getenv("MEDIA_ROOT", BASE_DIR / "media"))
PRIVATE_MEDIA_ROOT = Path(os.getenv("PRIVATE_MEDIA_ROOT", BASE_DIR / "private_media"))
BACKUP_ROOT = Path(os.getenv("BACKUP_ROOT", BASE_DIR / "backups"))
PRERENDER_ROOT = Path(os.getenv("PRERENDER_ROOT", BASE_DIR / "prerender_releases"))

# ===== SimpleUI 后台主题配置 =====
SIMPLEUI_HOME_INFO = False       # 关闭默认首页资讯
SIMPLEUI_ANALYSIS = False        # 关闭数据分析
SIMPLEUI_LOGO = '/static/images/logo.jpg'  # 后台 logo（后续替换）
SIMPLEUI_DEFAULT_THEME = 'e-blue.css'      # 默认主题：蓝色

SIMPLEUI_HOME_TITLE = '华丽电器内容管理'
SIMPLEUI_CONFIG = {
    # 保留 Django 自动生成的模型菜单，同时补充一个直达安全设置的入口。
    'system_keep': True,
    'menus': [
        {
            'name': '账号安全（TOTP）',
            'icon': 'fas fa-user-shield',
            'models': [
                {
                    'name': '绑定验证器双重验证',
                    'icon': 'fas fa-mobile-alt',
                    'url': '/admin/security/two-factor/setup/',
                },
                {
                    'name': '安全状态与登录记录',
                    'icon': 'fas fa-shield-alt',
                    'url': '/admin/security-center/',
                },
            ],
        },
    ],
}

REST_FRAMEWORK = {
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'EXCEPTION_HANDLER': 'main.api.api_exception_handler',
    'DEFAULT_THROTTLE_CLASSES': ['rest_framework.throttling.AnonRateThrottle'],
    'DEFAULT_THROTTLE_RATES': {'anon': '120/minute'},
}

AUTHENTICATION_BACKENDS = [
    "axes.backends.AxesStandaloneBackend",
    "django.contrib.auth.backends.ModelBackend",
]
AXES_FAILURE_LIMIT = 5
AXES_COOLOFF_TIME = 0.5
AXES_RESET_ON_SUCCESS = True
AXES_LOCKOUT_PARAMETERS = [["username"], ["ip_address"]]

CSRF_COOKIE_NAME = "huali_csrftoken"
CSRF_COOKIE_SAMESITE = "Lax"
CSRF_FAILURE_VIEW = "operations.csrf.csrf_failure"
CSRF_TRUSTED_ORIGINS = [
    item.strip() for item in os.getenv("CSRF_TRUSTED_ORIGINS", "http://localhost:5173,http://localhost:8000").split(",") if item.strip()
]

EMAIL_BACKEND = os.getenv("EMAIL_BACKEND", "django.core.mail.backends.console.EmailBackend")
EMAIL_HOST = os.getenv("EMAIL_HOST", "smtp.163.com")
EMAIL_PORT = int(os.getenv("EMAIL_PORT", "465"))
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD", "")
EMAIL_USE_SSL = os.getenv("EMAIL_USE_SSL", "true").lower() == "true"
DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL", EMAIL_HOST_USER or "webmaster@localhost")
SALES_EMAILS = [item.strip() for item in os.getenv("SALES_EMAILS", "").split(",") if item.strip()]
OPS_ALERT_EMAILS = [item.strip() for item in os.getenv("OPS_ALERT_EMAILS", "").split(",") if item.strip()]

FORM_SECURITY_KEY = os.getenv("FORM_SECURITY_KEY", SECRET_KEY)
BACKUP_ENCRYPTION_KEY = os.getenv("BACKUP_ENCRYPTION_KEY", "")
CLAMAV_ENABLED = os.getenv("CLAMAV_ENABLED", "false").lower() == "true"
CLAMAV_HOST = os.getenv("CLAMAV_HOST", "127.0.0.1")
CLAMAV_PORT = int(os.getenv("CLAMAV_PORT", "3310"))

S3_BACKUP_BUCKET = os.getenv("S3_BACKUP_BUCKET", "")
S3_ENDPOINT_URL = os.getenv("S3_ENDPOINT_URL", "")
S3_ACCESS_KEY_ID = os.getenv("S3_ACCESS_KEY_ID", "")
S3_SECRET_ACCESS_KEY = os.getenv("S3_SECRET_ACCESS_KEY", "")
S3_REGION = os.getenv("S3_REGION", "auto")
REQUIRE_SUPERUSER_2FA = os.getenv("REQUIRE_SUPERUSER_2FA", "false").lower() == "true"
BAIDU_SITE = os.getenv("BAIDU_SITE", "")
BAIDU_TOKEN = os.getenv("BAIDU_TOKEN", "")
INDEXNOW_KEY = os.getenv("INDEXNOW_KEY", "")
IMAGE_API_URL = os.getenv("IMAGE_API_URL", "")
IMAGE_API_KEY = os.getenv("IMAGE_API_KEY", "")
IMAGE_API_MODEL = os.getenv("IMAGE_API_MODEL", "gpt-image-2")

SPECTACULAR_SETTINGS = {
    'TITLE': '华丽电器公开 API',
    'DESCRIPTION': '产品、新闻、首页聚合与在线表单接口。',
    'VERSION': '1.0.0',
}
