# Generated by Django 6.0.7 on 2026-07-25 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lianxi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(max_length=100, verbose_name='联系人姓名')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='联系电话')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('subject', models.CharField(blank=True, max_length=100, verbose_name='主题')),
                ('message', models.TextField(verbose_name='留言内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='提交时间')),
            ],
            options={
                'verbose_name': '联系留言',
                'verbose_name_plural': '联系留言',
                'db_table': 'lianxi',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Xunpan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(max_length=100, verbose_name='联系人姓名')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='联系电话')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('company_brand', models.CharField(blank=True, max_length=200, verbose_name='公司/品牌')),
                ('project_type', models.CharField(blank=True, max_length=100, verbose_name='感兴趣的产品')),
                ('estimated_quantity', models.CharField(blank=True, max_length=100, verbose_name='预计数量')),
                ('country_region', models.CharField(blank=True, max_length=100, verbose_name='国家/地区')),
                ('detailed_requirements', models.TextField(verbose_name='详细需求')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='inquiry_attachments/%Y/%m/', verbose_name='附件')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='提交时间')),
            ],
            options={
                'verbose_name': '在线询盘',
                'verbose_name_plural': '在线询盘',
                'db_table': 'xunpan',
                'ordering': ['-created_at'],
            },
        ),
    ]
