# Generated by Django 6.0.7 on 2026-07-25 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lianxi',
            options={'ordering': ['-created_at'], 'verbose_name': '联系表单', 'verbose_name_plural': '联系表单'},
        ),
        migrations.AlterModelOptions(
            name='xunpan',
            options={'ordering': ['-created_at'], 'verbose_name': '询盘表单', 'verbose_name_plural': '询盘表单'},
        ),
    ]
