# Generated by Django 6.0.7 on 2026-07-25 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_lianxi_options_alter_xunpan_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='xunpan',
            name='product_model_snapshot',
            field=models.CharField(blank=True, max_length=80, verbose_name='产品型号快照'),
        ),
        migrations.AddField(
            model_name='xunpan',
            name='product_name_snapshot',
            field=models.CharField(blank=True, max_length=150, verbose_name='产品名称快照'),
        ),
    ]
