# Generated by Django 6.0.7 on 2026-07-26 16:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_xunpan_product_model_snapshot_and_more'),
        ('products', '0002_content_editor_group'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lianxi',
            name='assignee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_contacts', to=settings.AUTH_USER_MODEL, verbose_name='负责人'),
        ),
        migrations.AddField(
            model_name='lianxi',
            name='internal_note',
            field=models.TextField(blank=True, verbose_name='内部备注'),
        ),
        migrations.AddField(
            model_name='lianxi',
            name='last_followed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='最后跟进时间'),
        ),
        migrations.AddField(
            model_name='lianxi',
            name='status',
            field=models.CharField(choices=[('pending', '待处理'), ('following', '跟进中'), ('quoted', '已报价'), ('completed', '已完成'), ('invalid', '无效')], default='pending', max_length=20, verbose_name='处理状态'),
        ),
        migrations.AddField(
            model_name='xunpan',
            name='assignee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_inquiries', to=settings.AUTH_USER_MODEL, verbose_name='负责人'),
        ),
        migrations.AddField(
            model_name='xunpan',
            name='internal_note',
            field=models.TextField(blank=True, verbose_name='内部备注'),
        ),
        migrations.AddField(
            model_name='xunpan',
            name='last_followed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='最后跟进时间'),
        ),
        migrations.AddField(
            model_name='xunpan',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inquiries', to='products.product', verbose_name='关联产品'),
        ),
        migrations.AddField(
            model_name='xunpan',
            name='status',
            field=models.CharField(choices=[('pending', '待处理'), ('following', '跟进中'), ('quoted', '已报价'), ('completed', '已完成'), ('invalid', '无效')], default='pending', max_length=20, verbose_name='处理状态'),
        ),
    ]
