# Generated by Django 6.0.7 on 2026-07-26 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_lianxi_assignee_lianxi_internal_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lianxi',
            name='anonymized_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='匿名化时间'),
        ),
        migrations.AddField(
            model_name='lianxi',
            name='form_token_id',
            field=models.CharField(blank=True, max_length=36, verbose_name='表单令牌编号'),
        ),
        migrations.AddField(
            model_name='lianxi',
            name='ip_fingerprint',
            field=models.CharField(blank=True, db_index=True, max_length=64, verbose_name='IP 指纹'),
        ),
        migrations.AddField(
            model_name='lianxi',
            name='privacy_consented_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='隐私同意时间'),
        ),
    ]
