# Generated by Django 6.0.7 on 2026-07-26 18:14

import django.core.files.storage
import django.db.models.deletion
import pathlib
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_lianxi_anonymized_at_lianxi_form_token_id_and_more'),
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lianxi',
            name='privacy_policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contacts', to='operations.privacypolicy', verbose_name='同意的隐私政策'),
        ),
        migrations.AddField(
            model_name='lianxi',
            name='security_scan_status',
            field=models.CharField(default='not_applicable', max_length=30, verbose_name='安全检查状态'),
        ),
        migrations.AddField(
            model_name='xunpan',
            name='anonymized_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='匿名化时间'),
        ),
        migrations.AddField(
            model_name='xunpan',
            name='attachment_scan_status',
            field=models.CharField(default='not_applicable', max_length=30, verbose_name='附件扫描状态'),
        ),
        migrations.AddField(
            model_name='xunpan',
            name='form_token_id',
            field=models.CharField(blank=True, max_length=36, verbose_name='表单令牌编号'),
        ),
        migrations.AddField(
            model_name='xunpan',
            name='ip_fingerprint',
            field=models.CharField(blank=True, db_index=True, max_length=64, verbose_name='IP 指纹'),
        ),
        migrations.AddField(
            model_name='xunpan',
            name='privacy_consented_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='隐私同意时间'),
        ),
        migrations.AddField(
            model_name='xunpan',
            name='privacy_policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inquiries', to='operations.privacypolicy', verbose_name='同意的隐私政策'),
        ),
        migrations.AlterField(
            model_name='xunpan',
            name='attachment',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url=None, location=pathlib.PureWindowsPath('D:/13486/Desktop/企业网站/private_media')), upload_to='inquiry_attachments/%Y/%m/', verbose_name='附件'),
        ),
    ]
