# Generated by Django 6.0.7 on 2026-07-28 20:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='分类名称')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='固定 slug')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
            ],
            options={
                'verbose_name': '常见问题分类',
                'verbose_name_plural': '常见问题分类',
                'ordering': ('sort_order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='ContentSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='来源名称')),
                ('url', models.URLField(blank=True, verbose_name='来源网址')),
                ('reference_file', models.FileField(blank=True, upload_to='content_sources/', verbose_name='来源文件')),
                ('notes', models.TextField(blank=True, verbose_name='核验备注')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='核验时间')),
                ('is_public', models.BooleanField(default=False, verbose_name='前台显示来源')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='核验人')),
            ],
            options={
                'verbose_name': '内容来源',
                'verbose_name_plural': '内容来源',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='CompanyTimeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('published', '已发布'), ('archived', '归档')], default='draft', max_length=20, verbose_name='状态')),
                ('verification_status', models.CharField(choices=[('pending', '待核验'), ('verified', '已核验'), ('rejected', '已拒绝')], db_index=True, default='pending', max_length=20, verbose_name='核验状态')),
                ('is_demo', models.BooleanField(db_index=True, default=False, verbose_name='演示内容')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('year', models.PositiveSmallIntegerField(verbose_name='年份')),
                ('title', models.CharField(max_length=150, verbose_name='标题')),
                ('description', models.TextField(verbose_name='说明')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='company_content.contentsource', verbose_name='内容来源')),
            ],
            options={
                'verbose_name': '发展历程',
                'verbose_name_plural': '发展历程',
                'ordering': ('year', 'sort_order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('published', '已发布'), ('archived', '归档')], default='draft', max_length=20, verbose_name='状态')),
                ('verification_status', models.CharField(choices=[('pending', '待核验'), ('verified', '已核验'), ('rejected', '已拒绝')], db_index=True, default='pending', max_length=20, verbose_name='核验状态')),
                ('is_demo', models.BooleanField(db_index=True, default=False, verbose_name='演示内容')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name_zh', models.CharField(max_length=200, verbose_name='公司中文名')),
                ('name_en', models.CharField(blank=True, max_length=200, verbose_name='公司英文名')),
                ('brand_name', models.CharField(default='HUALI', max_length=50, verbose_name='英文品牌简称')),
                ('summary', models.TextField(verbose_name='公司简介')),
                ('legal_representative', models.CharField(blank=True, max_length=100, verbose_name='法人代表')),
                ('founded_on', models.DateField(blank=True, null=True, verbose_name='成立日期')),
                ('registered_capital', models.CharField(blank=True, max_length=100, verbose_name='注册资本')),
                ('credit_code', models.CharField(blank=True, max_length=50, verbose_name='统一社会信用代码')),
                ('registered_address', models.CharField(blank=True, max_length=300, verbose_name='注册地址')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='company_content.contentsource', verbose_name='内容来源')),
            ],
            options={
                'verbose_name': '企业资料',
                'verbose_name_plural': '企业资料',
            },
        ),
        migrations.CreateModel(
            name='CompanyFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('published', '已发布'), ('archived', '归档')], default='draft', max_length=20, verbose_name='状态')),
                ('verification_status', models.CharField(choices=[('pending', '待核验'), ('verified', '已核验'), ('rejected', '已拒绝')], db_index=True, default='pending', max_length=20, verbose_name='核验状态')),
                ('is_demo', models.BooleanField(db_index=True, default=False, verbose_name='演示内容')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('label', models.CharField(max_length=100, verbose_name='指标名称')),
                ('value', models.CharField(max_length=100, verbose_name='指标值')),
                ('unit', models.CharField(blank=True, max_length=30, verbose_name='单位')),
                ('description', models.CharField(blank=True, max_length=300, verbose_name='说明')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='company_content.contentsource', verbose_name='内容来源')),
            ],
            options={
                'verbose_name': '企业事实与指标',
                'verbose_name_plural': '企业事实与指标',
                'ordering': ('sort_order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='DealerBenefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('published', '已发布'), ('archived', '归档')], default='draft', max_length=20, verbose_name='状态')),
                ('verification_status', models.CharField(choices=[('pending', '待核验'), ('verified', '已核验'), ('rejected', '已拒绝')], db_index=True, default='pending', max_length=20, verbose_name='核验状态')),
                ('is_demo', models.BooleanField(db_index=True, default=False, verbose_name='演示内容')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('title', models.CharField(max_length=150, verbose_name='权益名称')),
                ('description', models.TextField(verbose_name='权益说明')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='company_content.contentsource', verbose_name='内容来源')),
            ],
            options={
                'verbose_name': '经销商权益',
                'verbose_name_plural': '经销商权益',
                'ordering': ('sort_order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('published', '已发布'), ('archived', '归档')], default='draft', max_length=20, verbose_name='状态')),
                ('verification_status', models.CharField(choices=[('pending', '待核验'), ('verified', '已核验'), ('rejected', '已拒绝')], db_index=True, default='pending', max_length=20, verbose_name='核验状态')),
                ('is_demo', models.BooleanField(db_index=True, default=False, verbose_name='演示内容')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('question', models.CharField(max_length=300, verbose_name='问题')),
                ('answer', models.TextField(verbose_name='回答')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='company_content.contentsource', verbose_name='内容来源')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='faqs', to='company_content.faqcategory', verbose_name='分类')),
            ],
            options={
                'verbose_name': '常见问题',
                'verbose_name_plural': '常见问题',
                'ordering': ('category__sort_order', 'sort_order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('published', '已发布'), ('archived', '归档')], default='draft', max_length=20, verbose_name='状态')),
                ('verification_status', models.CharField(choices=[('pending', '待核验'), ('verified', '已核验'), ('rejected', '已拒绝')], db_index=True, default='pending', max_length=20, verbose_name='核验状态')),
                ('is_demo', models.BooleanField(db_index=True, default=False, verbose_name='演示内容')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('kind', models.CharField(choices=[('headquarters', '总部'), ('factory', '工厂'), ('office', '办事处')], default='factory', max_length=20, verbose_name='地点类型')),
                ('name', models.CharField(max_length=150, verbose_name='地点名称')),
                ('address_zh', models.CharField(max_length=300, verbose_name='中文地址')),
                ('address_en', models.CharField(blank=True, max_length=300, verbose_name='英文地址')),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='经度')),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='纬度')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='电话')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='邮箱')),
                ('business_hours', models.CharField(blank=True, max_length=150, verbose_name='工作时间')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='company_content.contentsource', verbose_name='内容来源')),
            ],
            options={
                'verbose_name': '地点与联系方式',
                'verbose_name_plural': '地点与联系方式',
                'ordering': ('sort_order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='SupplyChainItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('published', '已发布'), ('archived', '归档')], default='draft', max_length=20, verbose_name='状态')),
                ('verification_status', models.CharField(choices=[('pending', '待核验'), ('verified', '已核验'), ('rejected', '已拒绝')], db_index=True, default='pending', max_length=20, verbose_name='核验状态')),
                ('is_demo', models.BooleanField(db_index=True, default=False, verbose_name='演示内容')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('kind', models.CharField(choices=[('process', '采购流程'), ('category', '核心采购品类'), ('requirement', '合作要求')], max_length=20, verbose_name='内容类型')),
                ('title', models.CharField(max_length=150, verbose_name='标题')),
                ('description', models.TextField(verbose_name='说明')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='company_content.contentsource', verbose_name='内容来源')),
            ],
            options={
                'verbose_name': '供应链内容',
                'verbose_name_plural': '供应链内容',
                'ordering': ('kind', 'sort_order', 'id'),
            },
        ),
    ]
