# Generated by Django 6.0.7 on 2026-07-29 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyfact',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='内容核验时间'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='内容核验时间'),
        ),
        migrations.AddField(
            model_name='companytimeline',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='内容核验时间'),
        ),
        migrations.AddField(
            model_name='dealerbenefit',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='内容核验时间'),
        ),
        migrations.AddField(
            model_name='faq',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='内容核验时间'),
        ),
        migrations.AddField(
            model_name='location',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='内容核验时间'),
        ),
        migrations.AddField(
            model_name='supplychainitem',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='内容核验时间'),
        ),
    ]
