# Generated by Django 6.0.7 on 2026-07-28 20:50

import django.db.models.deletion
import main.content_utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssetLicense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='许可名称')),
                ('license_type', models.CharField(choices=[('owned', '自有素材'), ('cc0', 'CC0'), ('cc_by', 'CC BY'), ('mit', 'MIT'), ('apache', 'Apache-2.0'), ('other', '其他'), ('unknown', '未知')], default='unknown', max_length=30, verbose_name='许可类型')),
                ('author', models.CharField(blank=True, max_length=150, verbose_name='作者/版权方')),
                ('source_url', models.URLField(blank=True, verbose_name='来源网址')),
                ('attribution', models.TextField(blank=True, verbose_name='署名要求')),
                ('allows_commercial_use', models.BooleanField(default=False, verbose_name='允许商业使用')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '素材许可',
                'verbose_name_plural': '素材许可台账',
            },
        ),
        migrations.CreateModel(
            name='MediaTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='标签名称')),
                ('slug', models.SlugField(unique=True, verbose_name='固定 slug')),
            ],
            options={
                'verbose_name': '媒体标签',
                'verbose_name_plural': '媒体标签',
            },
        ),
        migrations.CreateModel(
            name='MediaFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='文件夹名称')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='page_builder.mediafolder', verbose_name='上级文件夹')),
            ],
            options={
                'verbose_name': '媒体文件夹',
                'verbose_name_plural': '媒体文件夹',
                'ordering': ('sort_order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='PublicMediaAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='素材名称')),
                ('asset_type', models.CharField(choices=[('image', '图片'), ('video', '视频'), ('lottie', 'Lottie'), ('rive', 'Rive'), ('model_3d', '3D 模型'), ('other', '其他')], default='image', max_length=20, verbose_name='素材类型')),
                ('origin', models.CharField(choices=[('real', '真实素材'), ('ai', 'AI 占位素材'), ('open_source', '开源素材'), ('internal', '内部制作')], default='ai', max_length=20, verbose_name='素材来源类型')),
                ('file', models.FileField(upload_to='page_builder/assets/%Y/%m/', verbose_name='素材文件')),
                ('desktop_file', models.FileField(blank=True, upload_to='page_builder/variants/desktop/%Y/%m/', verbose_name='桌面变体')),
                ('mobile_file', models.FileField(blank=True, upload_to='page_builder/variants/mobile/%Y/%m/', verbose_name='手机变体')),
                ('preview_image', models.ImageField(blank=True, upload_to='page_builder/previews/%Y/%m/', validators=[main.content_utils.validate_image_upload], verbose_name='预览/封面')),
                ('alt_zh', models.CharField(blank=True, max_length=250, verbose_name='中文 Alt 草稿')),
                ('alt_en', models.CharField(blank=True, max_length=250, verbose_name='英文 Alt 草稿')),
                ('alt_reviewed', models.BooleanField(default=False, verbose_name='Alt 已审核')),
                ('is_decorative', models.BooleanField(default=False, verbose_name='装饰图')),
                ('focal_x_desktop', models.FloatField(default=0.5, verbose_name='桌面焦点 X')),
                ('focal_y_desktop', models.FloatField(default=0.5, verbose_name='桌面焦点 Y')),
                ('focal_x_mobile', models.FloatField(default=0.5, verbose_name='手机焦点 X')),
                ('focal_y_mobile', models.FloatField(default=0.5, verbose_name='手机焦点 Y')),
                ('width', models.PositiveIntegerField(default=0, editable=False, verbose_name='宽度')),
                ('height', models.PositiveIntegerField(default=0, editable=False, verbose_name='高度')),
                ('size', models.PositiveBigIntegerField(default=0, editable=False, verbose_name='文件大小')),
                ('sha256', models.CharField(blank=True, editable=False, max_length=64, verbose_name='SHA-256')),
                ('generation_prompt', models.TextField(blank=True, verbose_name='最终生成提示词')),
                ('generation_model', models.CharField(blank=True, max_length=100, verbose_name='生成模型')),
                ('generated_at', models.DateTimeField(blank=True, null=True, verbose_name='生成时间')),
                ('needs_replacement', models.BooleanField(db_index=True, default=True, verbose_name='上线前待替换')),
                ('is_approved', models.BooleanField(db_index=True, default=False, verbose_name='素材已审核')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='page_builder.mediafolder', verbose_name='文件夹')),
                ('license', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='page_builder.assetlicense', verbose_name='素材许可')),
                ('tags', models.ManyToManyField(blank=True, related_name='assets', to='page_builder.mediatag', verbose_name='标签')),
            ],
            options={
                'verbose_name': '公开媒体素材',
                'verbose_name_plural': '公开媒体库',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='MediaUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_type', models.CharField(max_length=80, verbose_name='引用类型')),
                ('owner_key', models.CharField(max_length=150, verbose_name='引用对象')),
                ('slot_key', models.CharField(blank=True, max_length=100, verbose_name='局部槽位')),
                ('is_override', models.BooleanField(default=False, verbose_name='页面独立覆盖')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usages', to='page_builder.publicmediaasset', verbose_name='素材')),
            ],
            options={
                'verbose_name': '素材引用',
                'verbose_name_plural': '素材引用关系',
            },
        ),
        migrations.CreateModel(
            name='AssetSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=100, unique=True, verbose_name='槽位键')),
                ('name', models.CharField(max_length=150, verbose_name='槽位名称')),
                ('description', models.CharField(blank=True, max_length=300, verbose_name='用途说明')),
                ('recommended_ratio', models.CharField(blank=True, max_length=30, verbose_name='建议比例')),
                ('min_width', models.PositiveIntegerField(default=0, verbose_name='最小宽度')),
                ('min_height', models.PositiveIntegerField(default=0, verbose_name='最小高度')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('current_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='active_slots', to='page_builder.publicmediaasset', verbose_name='当前素材')),
            ],
            options={
                'verbose_name': '全局素材槽位',
                'verbose_name_plural': '全局素材槽位',
            },
        ),
        migrations.AddConstraint(
            model_name='mediafolder',
            constraint=models.UniqueConstraint(fields=('parent', 'name'), name='unique_media_folder_name'),
        ),
        migrations.AddConstraint(
            model_name='mediausage',
            constraint=models.UniqueConstraint(fields=('asset', 'owner_type', 'owner_key', 'slot_key'), name='unique_media_usage'),
        ),
    ]
