# Generated by Django 6.0.7 on 2026-07-26 18:14

import django.core.files.storage
import django.db.models.deletion
import django.utils.timezone
import pathlib
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0005_lianxi_anonymized_at_lianxi_form_token_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255, verbose_name='文件名')),
                ('sha256', models.CharField(max_length=64, verbose_name='SHA-256')),
                ('size', models.PositiveBigIntegerField(verbose_name='大小')),
                ('status', models.CharField(max_length=20, verbose_name='状态')),
                ('remote_uploaded', models.BooleanField(default=False, verbose_name='已上传异地')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '备份记录',
                'verbose_name_plural': '备份记录',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='CaptchaChallenge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('answer_hash', models.CharField(max_length=64, verbose_name='答案摘要')),
                ('ip_fingerprint', models.CharField(db_index=True, max_length=64, verbose_name='IP 指纹')),
                ('expires_at', models.DateTimeField(verbose_name='过期时间')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='使用时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '验证码',
                'verbose_name_plural': '验证码',
            },
        ),
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=60, unique=True, verbose_name='模板键')),
                ('name', models.CharField(max_length=100, verbose_name='模板名称')),
                ('subject', models.CharField(max_length=200, verbose_name='邮件主题')),
                ('html_body', models.TextField(verbose_name='HTML 正文')),
                ('text_body', models.TextField(verbose_name='纯文本正文')),
                ('allowed_variables', models.CharField(blank=True, max_length=500, verbose_name='允许变量')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '邮件模板',
                'verbose_name_plural': '邮件模板',
            },
        ),
        migrations.CreateModel(
            name='FormToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(max_length=20, verbose_name='表单类型')),
                ('ip_fingerprint', models.CharField(db_index=True, max_length=64, verbose_name='IP 指纹')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='签发时间')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='使用时间')),
            ],
            options={
                'verbose_name': '表单令牌',
                'verbose_name_plural': '表单令牌',
            },
        ),
        migrations.CreateModel(
            name='PrerenderTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=500, unique=True, verbose_name='页面路径')),
                ('reason', models.CharField(blank=True, max_length=200, verbose_name='触发原因')),
                ('pending', models.BooleanField(db_index=True, default=True, verbose_name='等待重建')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '预渲染任务',
                'verbose_name_plural': '预渲染任务',
            },
        ),
        migrations.CreateModel(
            name='SystemAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(default='error', max_length=20, verbose_name='级别')),
                ('source', models.CharField(db_index=True, max_length=50, verbose_name='来源')),
                ('message', models.CharField(max_length=500, verbose_name='告警内容')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='解决时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '系统告警',
                'verbose_name_plural': '系统告警',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='TaskRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(db_index=True, max_length=40, verbose_name='任务类型')),
                ('status', models.CharField(db_index=True, max_length=20, verbose_name='状态')),
                ('summary', models.CharField(blank=True, max_length=500, verbose_name='摘要')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='开始时间')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
            ],
            options={
                'verbose_name': '任务运行记录',
                'verbose_name_plural': '任务运行记录',
                'ordering': ('-started_at',),
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(db_index=True, max_length=80, verbose_name='操作')),
                ('target_type', models.CharField(blank=True, max_length=80, verbose_name='对象类型')),
                ('target_id', models.CharField(blank=True, max_length=80, verbose_name='对象编号')),
                ('summary', models.CharField(blank=True, max_length=300, verbose_name='摘要')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='时间')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '审计日志',
                'verbose_name_plural': '审计日志',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='EmailTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('sales_notice', '销售通知'), ('customer_receipt', '客户回执'), ('follow_up', '跟进邮件'), ('ops_alert', '运维告警')], default='customer_receipt', max_length=30, verbose_name='邮件类型')),
                ('recipients', models.JSONField(default=list, verbose_name='收件人')),
                ('subject', models.CharField(max_length=200, verbose_name='主题')),
                ('html_body', models.TextField(verbose_name='HTML 正文')),
                ('text_body', models.TextField(verbose_name='纯文本正文')),
                ('status', models.CharField(choices=[('pending', '待发送'), ('sending', '发送中'), ('sent', '已发送'), ('failed', '失败')], db_index=True, default='pending', max_length=20, verbose_name='状态')),
                ('attempts', models.PositiveSmallIntegerField(default=0, verbose_name='尝试次数')),
                ('next_attempt_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='下次尝试')),
                ('last_error', models.CharField(blank=True, max_length=500, verbose_name='错误摘要')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='发送时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_tasks', to='main.lianxi')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('inquiry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_tasks', to='main.xunpan')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='operations.emailtemplate')),
            ],
            options={
                'verbose_name': '邮件任务',
                'verbose_name_plural': '邮件任务',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='EmailAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(storage=django.core.files.storage.FileSystemStorage(base_url=None, location=pathlib.PureWindowsPath('D:/13486/Desktop/企业网站/private_media')), upload_to='mail/%Y/%m/', verbose_name='附件')),
                ('original_name', models.CharField(max_length=255, verbose_name='原文件名')),
                ('size', models.PositiveBigIntegerField(default=0, verbose_name='大小')),
                ('scan_status', models.CharField(default='pending', max_length=30, verbose_name='扫描状态')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='operations.emailtask')),
            ],
            options={
                'verbose_name': '邮件附件',
                'verbose_name_plural': '邮件附件',
            },
        ),
        migrations.CreateModel(
            name='PrivacyPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=30, unique=True, verbose_name='版本号')),
                ('title_zh', models.CharField(max_length=200, verbose_name='中文标题')),
                ('body_zh', models.TextField(verbose_name='中文正文')),
                ('title_en', models.CharField(max_length=200, verbose_name='英文标题')),
                ('body_en', models.TextField(verbose_name='英文正文')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('published', '已发布'), ('retired', '已停用')], default='draft', max_length=20, verbose_name='状态')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='发布时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '隐私政策版本',
                'verbose_name_plural': '隐私政策版本',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='RecoveryCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_hash', models.CharField(max_length=64, verbose_name='恢复码摘要')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='使用时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otp_recovery_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '双重验证恢复码',
                'verbose_name_plural': '双重验证恢复码',
            },
        ),
    ]
