# Generated by Django 6.0.7 on 2026-07-26 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='backuprecord',
            name='migration_signature',
            field=models.CharField(blank=True, max_length=64, verbose_name='迁移版本摘要'),
        ),
    ]
