# Generated by Django 6.0.7 on 2026-07-28 20:50

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_backuprecord_migration_signature'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(db_index=True, max_length=50, verbose_name='任务类型')),
                ('status', models.CharField(choices=[('pending', '等待处理'), ('running', '处理中'), ('paused', '已暂停'), ('success', '已完成'), ('failed', '失败'), ('cancelled', '已取消')], db_index=True, default='pending', max_length=20, verbose_name='状态')),
                ('title', models.CharField(max_length=200, verbose_name='任务名称')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='任务参数')),
                ('result', models.JSONField(blank=True, default=dict, verbose_name='任务结果')),
                ('progress_current', models.PositiveIntegerField(default=0, verbose_name='当前进度')),
                ('progress_total', models.PositiveIntegerField(default=0, verbose_name='总进度')),
                ('attempts', models.PositiveSmallIntegerField(default=0, verbose_name='尝试次数')),
                ('max_attempts', models.PositiveSmallIntegerField(default=3, verbose_name='最大尝试次数')),
                ('next_attempt_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='下次执行时间')),
                ('last_error', models.CharField(blank=True, max_length=500, verbose_name='错误摘要')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '通用任务',
                'verbose_name_plural': '通用任务中心',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['status', 'next_attempt_at'], name='operations__status_2a2ad5_idx')],
            },
        ),
    ]
