# Generated by Django 6.0.7 on 2026-07-25 09:39

import django.db.models.deletion
import main.content_utils
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='标签名称')),
                ('slug', models.SlugField(unique=True, verbose_name='标签 slug')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
            ],
            options={
                'verbose_name': '产品标签',
                'verbose_name_plural': '产品标签',
                'ordering': ('sort_order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_web', models.ImageField(blank=True, editable=False, upload_to='products/web/', verbose_name='网页图')),
                ('image_thumb', models.ImageField(blank=True, editable=False, upload_to='products/thumbs/', verbose_name='缩略图')),
                ('focal_x', models.FloatField(default=0.5, verbose_name='焦点 X')),
                ('focal_y', models.FloatField(default=0.5, verbose_name='焦点 Y')),
                ('name', models.CharField(max_length=150, verbose_name='产品名称')),
                ('model', models.CharField(max_length=80, unique=True, verbose_name='产品型号')),
                ('level', models.CharField(max_length=50, verbose_name='产品等级')),
                ('summary', models.CharField(max_length=200, verbose_name='产品摘要')),
                ('description', models.TextField(verbose_name='详细说明')),
                ('description_text', models.TextField(blank=True, editable=False, verbose_name='说明纯文本')),
                ('image', models.ImageField(blank=True, upload_to='products/original/', validators=[main.content_utils.validate_image_upload], verbose_name='产品主图')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('published', '已发布'), ('archived', '归档')], default='draft', max_length=20, verbose_name='状态')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='公开排序')),
                ('is_featured', models.BooleanField(default=False, verbose_name='首页推荐')),
                ('featured_order', models.PositiveIntegerField(default=0, verbose_name='推荐排序')),
                ('homepage_badge', models.CharField(blank=True, max_length=20, verbose_name='首页角标')),
                ('seo_title', models.CharField(blank=True, max_length=160, verbose_name='SEO 标题')),
                ('seo_description', models.CharField(blank=True, max_length=300, verbose_name='SEO 描述')),
                ('search_text', models.TextField(blank=True, editable=False, verbose_name='搜索索引')),
                ('first_published_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='首次发布时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_products', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('related_products', models.ManyToManyField(blank=True, to='products.product', verbose_name='手动相关产品')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_products', to=settings.AUTH_USER_MODEL, verbose_name='最后修改人')),
            ],
            options={
                'verbose_name': '产品',
                'verbose_name_plural': '产品',
                'ordering': ('sort_order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='ProductApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='场景名称')),
                ('description', models.CharField(blank=True, max_length=250, verbose_name='场景说明')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='products.product', verbose_name='产品')),
            ],
            options={
                'verbose_name': '应用场景',
                'verbose_name_plural': '应用场景',
                'ordering': ('sort_order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_web', models.ImageField(blank=True, editable=False, upload_to='products/web/', verbose_name='网页图')),
                ('image_thumb', models.ImageField(blank=True, editable=False, upload_to='products/thumbs/', verbose_name='缩略图')),
                ('focal_x', models.FloatField(default=0.5, verbose_name='焦点 X')),
                ('focal_y', models.FloatField(default=0.5, verbose_name='焦点 Y')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='分类名称')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='固定 slug')),
                ('description', models.CharField(blank=True, max_length=300, verbose_name='分类简介')),
                ('image', models.ImageField(blank=True, upload_to='products/categories/original/', validators=[main.content_utils.validate_image_upload], verbose_name='分类封面')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '产品分类',
                'verbose_name_plural': '产品分类',
                'ordering': ('sort_order', 'id'),
                'indexes': [models.Index(fields=['is_active', 'sort_order'], name='products_pr_is_acti_97c91e_idx')],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.productcategory', verbose_name='产品分类'),
        ),
        migrations.CreateModel(
            name='ProductDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='资料名称')),
                ('document_type', models.CharField(choices=[('manual', '说明书'), ('catalog', '产品目录'), ('certificate', '认证文件'), ('other', '其他')], max_length=30, verbose_name='资料类型')),
                ('language', models.CharField(choices=[('zh', '中文'), ('en', '英文'), ('de', '德语'), ('es', '西班牙语'), ('fr', '法语'), ('ru', '俄语'), ('ar', '阿拉伯语'), ('other', '其他')], default='zh', max_length=20, verbose_name='语言')),
                ('file', models.FileField(upload_to='products/documents/', validators=[main.content_utils.validate_pdf_upload], verbose_name='PDF 文件')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='products.product', verbose_name='产品')),
            ],
            options={
                'verbose_name': '产品资料',
                'verbose_name_plural': '产品资料',
                'ordering': ('sort_order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='ProductGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_web', models.ImageField(blank=True, editable=False, upload_to='products/web/', verbose_name='网页图')),
                ('image_thumb', models.ImageField(blank=True, editable=False, upload_to='products/thumbs/', verbose_name='缩略图')),
                ('focal_x', models.FloatField(default=0.5, verbose_name='焦点 X')),
                ('focal_y', models.FloatField(default=0.5, verbose_name='焦点 Y')),
                ('image', models.ImageField(upload_to='products/gallery/original/', validators=[main.content_utils.validate_image_upload], verbose_name='详情图片')),
                ('alt_text', models.CharField(max_length=200, verbose_name='图片说明/Alt')),
                ('caption', models.CharField(blank=True, max_length=250, verbose_name='图片说明')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='products.product', verbose_name='产品')),
            ],
            options={
                'verbose_name': '产品图库',
                'verbose_name_plural': '产品图库',
                'ordering': ('sort_order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='ProductHighlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='特点标题')),
                ('description', models.CharField(max_length=300, verbose_name='特点说明')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highlights', to='products.product', verbose_name='产品')),
            ],
            options={
                'verbose_name': '产品特点',
                'verbose_name_plural': '产品特点',
                'ordering': ('sort_order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='ProductSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='参数名称')),
                ('value', models.CharField(max_length=150, verbose_name='参数值')),
                ('show_on_card', models.BooleanField(default=False, verbose_name='卡片展示')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specifications', to='products.product', verbose_name='产品')),
            ],
            options={
                'verbose_name': '产品参数',
                'verbose_name_plural': '产品参数',
                'ordering': ('sort_order', 'id'),
            },
        ),
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='products', to='products.producttag', verbose_name='产品标签'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['status', 'sort_order'], name='products_pr_status_9c8056_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category', 'status', 'sort_order'], name='products_pr_categor_31074b_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_featured', 'featured_order'], name='products_pr_is_feat_b86213_idx'),
        ),
    ]
