# Generated by Django 6.0.7 on 2026-07-28 20:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_content_editor_group'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StandardParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_zh', models.CharField(max_length=100, unique=True, verbose_name='中文名称')),
                ('name_en', models.CharField(blank=True, max_length=100, verbose_name='英文名称')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='固定 slug')),
                ('value_type', models.CharField(choices=[('number', '数值'), ('enum', '枚举'), ('text', '文本'), ('boolean', '是/否')], default='number', max_length=20, verbose_name='数据类型')),
                ('standard_unit', models.CharField(blank=True, max_length=30, verbose_name='标准单位')),
                ('aliases_zh', models.TextField(blank=True, help_text='每行一个别名。', verbose_name='中文别名')),
                ('aliases_en', models.TextField(blank=True, help_text='每行一个别名。', verbose_name='英文别名')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '标准参数字典',
                'verbose_name_plural': '标准参数字典',
                'ordering': ('sort_order', 'id'),
            },
        ),
        migrations.AddField(
            model_name='product',
            name='is_demo',
            field=models.BooleanField(db_index=True, default=False, verbose_name='演示产品'),
        ),
        migrations.AddField(
            model_name='product',
            name='source_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='资料来源名称'),
        ),
        migrations.AddField(
            model_name='product',
            name='source_url',
            field=models.URLField(blank=True, verbose_name='资料来源网址'),
        ),
        migrations.AddField(
            model_name='product',
            name='verification_status',
            field=models.CharField(choices=[('pending', '待核验'), ('verified', '已核验'), ('rejected', '已拒绝')], db_index=True, default='pending', max_length=20, verbose_name='核验状态'),
        ),
        migrations.AddField(
            model_name='product',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='核验时间'),
        ),
        migrations.AddField(
            model_name='productdocument',
            name='disclaimer',
            field=models.CharField(blank=True, max_length=300, verbose_name='测试免责声明'),
        ),
        migrations.AddField(
            model_name='productdocument',
            name='is_demo',
            field=models.BooleanField(db_index=True, default=False, verbose_name='演示资料'),
        ),
        migrations.AddField(
            model_name='productspecification',
            name='normalized_number',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='用于单位归一化比较，不改变前台展示的原始值。', max_digits=18, null=True, verbose_name='标准数值'),
        ),
        migrations.AddField(
            model_name='productspecification',
            name='normalized_text',
            field=models.CharField(blank=True, max_length=150, verbose_name='标准文本值'),
        ),
        migrations.AddField(
            model_name='productspecification',
            name='standard_parameter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_values', to='products.standardparameter', verbose_name='标准参数'),
        ),
        migrations.CreateModel(
            name='ParameterMappingSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_name', models.CharField(db_index=True, max_length=100, verbose_name='原参数名称')),
                ('matched_alias', models.CharField(max_length=100, verbose_name='命中的名称/别名')),
                ('confidence', models.DecimalField(decimal_places=3, default=1, max_digits=4, verbose_name='建议置信度')),
                ('affected_count', models.PositiveIntegerField(default=0, verbose_name='待映射参数数')),
                ('status', models.CharField(choices=[('pending', '待确认'), ('accepted', '已接受'), ('rejected', '已拒绝')], default='pending', max_length=20, verbose_name='确认状态')),
                ('review_notes', models.CharField(blank=True, max_length=300, verbose_name='审核备注')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='审核时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='审核人')),
                ('suggested_parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mapping_suggestions', to='products.standardparameter', verbose_name='建议标准参数')),
            ],
            options={
                'verbose_name': '参数映射建议',
                'verbose_name_plural': '参数映射建议',
                'ordering': ('status', 'source_name', 'id'),
                'constraints': [models.UniqueConstraint(fields=('source_name', 'suggested_parameter'), name='unique_parameter_mapping_suggestion')],
            },
        ),
        migrations.CreateModel(
            name='StandardParameterOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.SlugField(max_length=80, verbose_name='标准值')),
                ('label_zh', models.CharField(max_length=100, verbose_name='中文显示')),
                ('label_en', models.CharField(blank=True, max_length=100, verbose_name='英文显示')),
                ('aliases', models.TextField(blank=True, help_text='每行一个中英文别名。', verbose_name='别名')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='products.standardparameter', verbose_name='标准参数')),
            ],
            options={
                'verbose_name': '标准参数枚举值',
                'verbose_name_plural': '标准参数枚举值',
                'ordering': ('sort_order', 'id'),
                'constraints': [models.UniqueConstraint(fields=('parameter', 'value'), name='unique_standard_parameter_option')],
            },
        ),
    ]
